FROM adoptopenjdk/openjdk11

RUN apt update && apt install -y git-core

RUN git clone -b master --single-branch https://github.com/dev-team-avengers/ToyLog.git
RUN mv ToyLog toylog-api
WORKDIR toylog-api

RUN chmod a+x gradlew
RUN ./gradlew bootjar --stacktrace
RUN ls .
RUN ls build/libs/

EXPOSE 8080
CMD java -Dspring.profiles.active=dev -Duser.timezone=Asia/Seoul -jar build/libs/toylog-api.jar
